labs14-brav/Backend

.editorconfig, .gitignore, package-lock.json, package.json, server/app.js, server/controllers/RootController.js, server/routes/root_router.js
Setup an initial express application.
=> Initial deployment

package-lock.json
Fixed package.lock merge conflict with two histories
=> fixing package.lock merge conflict

data/dbConfig.js, server/controllers/RootController.js
Changed DB_ENV to NODE_ENV
Added some error messaging for .get /users
=> Quick changes discussed during zoom

__test__/users.test.js
=> add test suite for users route

server/controllers/RootController.js, server/models/rootModel.js
Added a limit and offset query parameter 
=> added limits and offset to user endpoint

README.md, package.json, server/app.js
Began to fill out README content.
=> Setup work for README

knexfile.js, server/controllers/RootController.js
Add support for Heroku staging environments.
=> Support staging db

package-lock.json, server/controllers/RootController.js, server/middleware/restricted.js, server/routes/root_router.js
Created a simple middleware that verifies if the Token provided on headers.authorization is valid. This will be useful for protecting endpoints in the future. I tested manually using Insomnia and a dummy endpoint. 
=> Restricted middleware

data/migrations/20190710142730_create_users.js, data/seeds/001-users.js, data/seeds/002-cases.js, package-lock.json, package.json
This adds seed data to the database for `users` and `cases`.
=> Add fake data

server/models/rootModel.js
Needed to fix the rootModel methods.
=> Fix rootmodel

server/controllers/CasesController.js, server/models/Case.js
Ensure case list displays only cases for that user.
=> Filter cases by user

package-lock.json, server/controllers/RootController.js, server/controllers/UsersController.js, server/models/rootModel.js, server/models/userModel.js, server/routes/users_router.js
Fixed the location of the mediator upgrade controller
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
=> refactored mediator upgrade controller

data/migrations/20190724114126_create_cases.js, data/migrations/20190726133345_create_addendums.js, data/seeds/001-users.js, data/seeds/002-cases.js, server/routes/cases_router.js
Apply fix for inserting cases with seeded data.
=> Fix cases insert

data/migrations/20190724114126_create_cases.js, server/controllers/CasesController.js, server/models/Case.js, server/routes/cases_router.js
=> Accept decline mediation request

server/controllers/CasesController.js, server/models/Case.js, server/routes/cases_router.js, server/routes/mediators_router.js
Changed Models to retrieve individual cases based on the mediator id passed in.
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
=> Filter mediator cases fix

data/migrations/20190710142730_create_users.js, server/controllers/MediatorsController.js, server/controllers/UsersController.js, server/models/Mediator.js, server/routes/mediators_router.js
Adding filters for mediators search.
=> Filter mediators

server/controllers/UsersController.js
Added License to editUser model in Mediator Upgrade controller
=> added license to MediatorUpdgrade controller

server/middleware/require_body.js
Ensure that our `require_body` middleware also checks the length of required body fields.
=> Length check middleware

__test__/route/cases_router.test.js, __test__/route/root_router.test.js, server/controllers/CasesController.js, server/models/Case.js, server/routes/cases_router.js
Added the endpoint for deleting a case. I was sure to check if the case was owned by the user trying to delete it.
=> Add DELETE /cases/:id and fix tests

server/controllers/UsersController.js, server/routes/users_router.js
Added require body middleware to the Mediator upgrade route on the user router. It checks for all of the fields of the registration form. 
=> Fixed mediator upgrade to include required body middleware

server/initializers/emails.js
Added transactional template ID to emails.js
=> Changed out sample email with a transactional template I created

data/migrations/20190814121434_create_invoices.js, server/controllers/InvoicesController.js, server/models/Invoice.js, server/routes/invoices_router.js
Dynamically set Stripe Session details from invoice.
=> Dynamically set Stripe Session details

server/controllers/InvoicesController.js, server/models/Invoice.js, server/routes/invoices_router.js
=> Set callback URL for handling successful checkout

data/seeds/002-cases.js, data/seeds/004-invoices.js
added seeds for cases and invoices
=> Invoice seeds

data/migrations/20190814121434_create_invoices.js, package-lock.json, server/controllers/InvoicesController.js, server/models/Invoice.js
Added mediator info to invoice endpoint so users get a more detailed invoice record in their case overview page.
=> Added mediator info to invoice findbycaseid endpoint

server/controllers/InvoicesController.js
changes the amount charged per transaction. 
=> editing amount taken

data/migrations/20190710142730_create_users.js
Fixed bug in mediator registration form
=> updated migration file for users

server/initializers/SendGrid.js
=> Added $ to invoice.

data/migrations/20190823101158_create_documents.js, server/controllers/CasesController.js, server/controllers/DocumentsController.js, server/models/Case.js, server/models/Documents.js, server/routes/cases_router.js
Created table and route for  documents.
=> Firebase storage

data/migrations/20190710142730_create_users.js
Added a field in the user object to save the image url
=> added a field in the user object to save the image url

data/migrations/20191007185816_create_relationships.js, server/controllers/MediatorsController.js, server/controllers/RelationshipsController.js, server/models/Relationships.js
I have added a Model and Controller for the Relationships table. I also added a line where new mediator cases are made, which will immediately create a new relationship between the user who made the case and the mediator who is considering it. The relationship is established even before the mediator accepts the case, in case the user and mediator wish to discuss things in the messaging app.
=> Victor goico

data/migrations/20190710142730_create_users.js, data/migrations/20190724114126_create_cases.js
I added a field to the user table so that we can identify if the user has been on boarded to the app or not. If the user is not on boarded they will be redirected to an on boarding form. 
=> Onboarding

data/migrations/20190710142730_create_users.js
updated text to boolean on the is_onboarded field in the users table
=> updated text to boolean on the is_onboarded field in the users table
